name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset debug -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: Build
        run: cmake --build --preset debug --parallel

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset debug -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: Build test executable
        run: cmake --build --preset debug --target slot_map_tests --parallel
      - name: Test
        run: ctest --preset debug
